### ISSUE TITLE
Podemos mergear a versão que contempla typeahed em master?

### ISSUE THREAD

**Issue by afonso-praca** [vtex/vtex-ng-filter#3]

**Comment by gugiserman** [comment]
@afonso-praca eu acho que podemos, afonso, mas nao foi pra select2 em vez de typeahead?

ai ja eh uma dependencia mais especifica

**Comment by afonso-praca** [comment]
foi sim, vamos deixar assim por enquanto entao. e depois pensamos melhor :-)

--
*Afonso Praça*
Software Developer
VTEX - e-Commerce Cloud Software
+55 21 979.151515
www.vtex.com
lab.vtex.com

2015-11-12 15:03 GMT-02:00 Gustavo Giserman <notifications@github.com>:

**Comment by gugiserman** [comment]
ok
